/**
 * Aquaculture report data shape — Phase B Step 22.
 *
 * Pure data assembly. The PDF/Excel renderer (which lives in
 * src/utils/reportGenerator.ts and imports jsPDF) consumes this shape.
 *
 * Caller pattern:
 *   const data = await assembleAquacultureReport({ farmId, flockId, supabase });
 *   await generateAquaculturePDF(data);  // future addition to reportGenerator.ts
 *   await generateAquacultureExcel(data); // ditto
 */

export interface AquaculturePondReport {
  farmName: string;
  pondName: string;
  pondType: string;
  cycleStartDate: string;
  reportPeriod: { startDate: string; endDate: string };
  stocking: {
    fingerlingCount: number;
    avgInitialWeightG: number;
    pondSizeSqm: number | null;
    sourceHatchery?: string;
  };
  current: {
    week: number;
    abwG: number | null;
    biomassKg: number;
    survivalPct: number;
    densityFishPerSqm: number | null;
  };
  growth: {
    sgrPercentDay: number | null;
    fcr: number | null;
    weightGainKg: number;
  };
  feed: {
    totalFeedKg: number;
    feedTypes: Array<{ name: string; quantityKg: number }>;
    feedCostTotal: number;
  };
  waterQuality: {
    samplesTaken: number;
    emergencyEventsCount: number;
    avgDoMgL: number | null;
    avgPh: number | null;
  };
  mortality: {
    totalDeaths: number;
    causes: Array<{ cause: string; count: number }>;
  };
  harvest: {
    eventsCount: number;
    biomassHarvestedKg: number;
    revenue: number;
  };
  financials: {
    totalExpenses: number;
    totalRevenue: number;
    netProfit: number;
    costPerKgBiomass: number;
    marginPercent: number;
  };
  notes: string;
}

/**
 * Format the report as a plain-text Markdown document.
 * The PDF renderer can convert this; for now this is what we ship for
 * "share via WhatsApp" or "copy to clipboard" actions.
 */
export function formatAquacultureReportMarkdown(r: AquaculturePondReport): string {
  const fmt = (n: number, decimals = 0) =>
    n.toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals });

  return `# Pond Report: ${r.pondName}

**Farm:** ${r.farmName}
**Species:** ${r.pondType}
**Cycle started:** ${r.cycleStartDate}
**Report period:** ${r.reportPeriod.startDate} → ${r.reportPeriod.endDate}

## Stocking
- Fingerlings stocked: ${fmt(r.stocking.fingerlingCount)} (avg ${r.stocking.avgInitialWeightG.toFixed(1)} g)
- Pond size: ${r.stocking.pondSizeSqm ? `${r.stocking.pondSizeSqm} m²` : 'not set'}
${r.stocking.sourceHatchery ? `- Source: ${r.stocking.sourceHatchery}` : ''}

## Current State (Week ${r.current.week})
- ABW: ${r.current.abwG !== null ? `${r.current.abwG.toFixed(1)} g` : '—'}
- Biomass: ${fmt(r.current.biomassKg, 1)} kg
- Survival: ${r.current.survivalPct.toFixed(1)}%
- Density: ${r.current.densityFishPerSqm !== null ? `${r.current.densityFishPerSqm.toFixed(1)} fish/m²` : '—'}

## Growth
- SGR: ${r.growth.sgrPercentDay !== null ? `${r.growth.sgrPercentDay.toFixed(2)} %/day` : '—'}
- FCR: ${r.growth.fcr !== null ? r.growth.fcr.toFixed(2) : '—'}
- Total weight gain: ${fmt(r.growth.weightGainKg, 1)} kg

## Feed
- Total feed used: ${fmt(r.feed.totalFeedKg, 1)} kg
- Total feed cost: ${fmt(r.feed.feedCostTotal)}
${r.feed.feedTypes.map(ft => `  - ${ft.name}: ${fmt(ft.quantityKg, 1)} kg`).join('\n')}

## Water Quality
- Samples taken: ${r.waterQuality.samplesTaken}
- Emergency events: ${r.waterQuality.emergencyEventsCount}
- Avg DO: ${r.waterQuality.avgDoMgL !== null ? `${r.waterQuality.avgDoMgL.toFixed(2)} mg/L` : '—'}
- Avg pH: ${r.waterQuality.avgPh !== null ? r.waterQuality.avgPh.toFixed(2) : '—'}

## Mortality
- Total deaths: ${fmt(r.mortality.totalDeaths)}
${r.mortality.causes.map(c => `  - ${c.cause}: ${c.count}`).join('\n')}

## Harvest
- Events: ${r.harvest.eventsCount}
- Biomass harvested: ${fmt(r.harvest.biomassHarvestedKg, 1)} kg
- Revenue: ${fmt(r.harvest.revenue)}

## Financials
- Total expenses: ${fmt(r.financials.totalExpenses)}
- Total revenue: ${fmt(r.financials.totalRevenue)}
- Net profit: ${fmt(r.financials.netProfit)}
- Cost per kg biomass: ${fmt(r.financials.costPerKgBiomass)}
- Margin: ${r.financials.marginPercent.toFixed(1)}%

${r.notes ? `\n## Notes\n${r.notes}` : ''}

---
Generated by EdenTrack on ${new Date().toLocaleDateString()}`;
}
