import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { CreditScoreResult } from './creditScore';

interface PDFInput {
  farmName: string;
  ownerName: string;
  ownerEmail: string;
  location: string | null;
  currencyCode: string;
  score: CreditScoreResult;
}

const TONE_GREEN: [number, number, number] = [61, 95, 66];
const TONE_GREY: [number, number, number] = [110, 110, 110];

function tierColor(tier: CreditScoreResult['tier']): [number, number, number] {
  switch (tier) {
    case 'excellent':
      return [16, 122, 65];
    case 'good':
      return [22, 132, 90];
    case 'fair':
      return [180, 132, 0];
    case 'building':
      return [200, 90, 30];
    case 'insufficient':
      return [120, 30, 30];
  }
}

function fmtMoney(n: number, code: string): string {
  return `${code} ${new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 }).format(Math.round(n))}`;
}

export function generateCreditworthinessPDF(input: PDFInput): Blob {
  const { farmName, ownerName, ownerEmail, location, currencyCode, score } = input;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 42;
  let y = 0;

  // Header strip
  doc.setFillColor(...TONE_GREEN);
  doc.rect(0, 0, pageW, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Creditworthiness Report', M, 32);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by EdenTrack — farm management & operational data record', M, 50);

  y = 100;
  doc.setTextColor(0, 0, 0);

  // Farm identity
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(farmName, M, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...TONE_GREY);
  const idLines = [
    `Owner: ${ownerName} <${ownerEmail}>`,
    location ? `Location: ${location}` : null,
    `Report generated: ${new Date(score.generatedAt).toLocaleString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })}`,
  ].filter(Boolean) as string[];
  idLines.forEach((line) => {
    doc.text(line, M, y);
    y += 14;
  });
  y += 8;

  // Big score box
  const boxH = 90;
  doc.setDrawColor(220, 220, 220);
  doc.setFillColor(248, 250, 248);
  doc.roundedRect(M, y, pageW - 2 * M, boxH, 8, 8, 'FD');

  doc.setTextColor(...TONE_GREY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('OVERALL SCORE', M + 16, y + 22);

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(40);
  doc.text(`${score.total}`, M + 16, y + 62);
  doc.setFontSize(16);
  doc.setTextColor(...TONE_GREY);
  doc.text('/ 100', M + 16 + 60, y + 62);

  // Tier badge on the right
  const [tr, tg, tb] = tierColor(score.tier);
  doc.setFillColor(tr, tg, tb);
  const badgeW = 130;
  const badgeX = pageW - M - badgeW - 16;
  doc.roundedRect(badgeX, y + 30, badgeW, 36, 6, 6, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(score.tierLabel.toUpperCase(), badgeX + badgeW / 2, y + 53, { align: 'center' });

  y += boxH + 16;

  // Component breakdown
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Score breakdown', M, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Component', 'Score', 'Detail']],
    body: score.components.map((c) => [c.label, `${c.score} / ${c.maxScore}`, c.detail]),
    theme: 'striped',
    headStyles: { fillColor: TONE_GREEN, textColor: [255, 255, 255], fontStyle: 'bold' },
    margin: { left: M, right: M },
    columnStyles: {
      0: { cellWidth: 150, fontStyle: 'bold' },
      1: { cellWidth: 70, halign: 'center' },
      2: { cellWidth: 'auto' },
    },
    styles: { fontSize: 10, cellPadding: 6 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Operations & financials section
  if (y > pageH - 200) {
    doc.addPage();
    y = M;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Operations & financials (last 12 months)', M, y);
  y += 8;

  const m = score.metrics;
  autoTable(doc, {
    startY: y,
    body: [
      ['Time on platform', `${m.daysOnPlatform} days`],
      ['Active flocks/ponds', `${m.activeFlockCount}`],
      ['Total animals on farm', `${m.totalAnimals.toLocaleString()}`],
      ['Total revenue (12mo)', fmtMoney(m.totalRevenueLast12mo, currencyCode)],
      ['Total expenses (12mo)', fmtMoney(m.totalExpensesLast12mo, currencyCode)],
      ['Net result (12mo)', fmtMoney(m.netLast12mo, currencyCode)],
      ['Sales records (12mo)', `${m.salesEntryCount}`],
      ['Expense records (12mo)', `${m.expenseEntryCount}`],
      ['Mortality count (12mo)', `${m.mortalityCount.toLocaleString()}`],
      ['Mortality rate', `${m.mortalityRatePct.toFixed(1)}%`],
      [
        'Vaccinations on schedule',
        m.vaccinationsOnSchedulePct == null ? 'No schedule yet' : `${m.vaccinationsOnSchedulePct.toFixed(0)}%`,
      ],
      ['Active days (last 90)', `${m.activeDaysLast90}`],
    ],
    theme: 'plain',
    margin: { left: M, right: M },
    columnStyles: {
      0: { cellWidth: 220, textColor: [80, 80, 80] },
      1: { cellWidth: 'auto', fontStyle: 'bold' },
    },
    styles: { fontSize: 10, cellPadding: 4 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Methodology / disclaimer
  if (y > pageH - 180) {
    doc.addPage();
    y = M;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Methodology', M, y);
  y += 14;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TONE_GREY);
  const methodology = [
    'This score reflects operational and financial discipline as recorded by the farmer in the EdenTrack',
    'platform over the past 12 months. It does not constitute formal credit advice and should be combined',
    'with the bank’s own due diligence (collateral, KYC, character references). EdenTrack does not vouch',
    'for the accuracy of farmer-entered data; however, the activity log (active days) is system-recorded',
    'and serves as a proxy for engagement and operational discipline.',
  ];
  methodology.forEach((line) => {
    doc.text(line, M, y);
    y += 12;
  });
  y += 6;

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Tier definitions', M, y);
  y += 14;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TONE_GREY);
  const tiers = [
    '80–100 Excellent: strong operational discipline, consistent records, healthy margins.',
    '65–79 Good: regular tracking, profitable operation, minor gaps acceptable.',
    '50–64 Fair: viable operation but inconsistent recording. Loan possible with conditions.',
    '35–49 Building: encourage 3 more months of tracking before re-assessment.',
    '0–34 Insufficient: too little data to assess.',
  ];
  tiers.forEach((line) => {
    doc.text(line, M, y);
    y += 12;
  });

  // Footer with timestamp + page numbers on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TONE_GREY);
    doc.text(`EdenTrack Creditworthiness Report · ${farmName}`, M, pageH - 18);
    doc.text(`Page ${i} of ${pageCount}`, pageW - M, pageH - 18, { align: 'right' });
  }

  return doc.output('blob');
}

export function downloadCreditworthinessPDF(input: PDFInput) {
  const blob = generateCreditworthinessPDF(input);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const safeName = input.farmName.replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase();
  a.href = url;
  a.download = `creditworthiness-${safeName}-${input.score.generatedAt.slice(0, 10)}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
