import { Flock } from '../types/database';

interface WeightAnalysis {
  average: number;
  count: number;
  min: number;
  max: number;
  stdDev: number;
  cv: number;
  totalFlockWeight: number;
  dailyGain?: number;
  daysElapsed?: number;
  previousWeight?: number;
  marketStatus?: string;
  uniformity?: string;
  growthRating?: string;
  recommendation?: string;
}

interface Farm {
  name: string;
  id: string;
}

export function formatWeightReportForWhatsApp(
  analysis: WeightAnalysis,
  flock: Flock,
  farm: Farm
): string {
  const flockAge = calculateFlockAge(flock.arrival_date);
  const percentOfTarget = calculatePercentOfTarget(analysis.average, flockAge, flock.type);
  const uniformityRating = getUniformityRating(analysis.cv);

  let message = `*🐔 WEIGHT CHECK REPORT*\n`;
  message += `━━━━━━━━━━━━━━━━━━━━\n\n`;

  message += `*Farm:* ${farm.name}\n`;
  message += `*Flock:* ${flock.name} (${flock.type})\n`;
  message += `*Date:* ${new Date().toLocaleDateString()}\n\n`;

  message += `*FLOCK INFO*\n`;
  message += `- Current Age: Week ${flockAge}\n`;
  message += `- Total Birds: ${flock.current_count?.toLocaleString()}\n`;
  message += `- Birds Sampled: ${analysis.count}\n\n`;

  message += `*WEIGHT ANALYSIS*\n`;
  message += `- Average Weight: *${analysis.average.toFixed(2)} kg*\n`;
  message += `- Performance: *${percentOfTarget.toFixed(0)}%* of target\n`;
  message += `- Weight Range: ${analysis.min.toFixed(2)} - ${analysis.max.toFixed(2)} kg\n`;
  message += `- Uniformity: *${uniformityRating}* (CV: ${analysis.cv.toFixed(1)}%)\n\n`;

  message += `*FLOCK ESTIMATE*\n`;
  message += `- Total Weight: ${analysis.totalFlockWeight.toFixed(0)} kg\n`;
  message += `- Confidence: High\n\n`;

  if (analysis.dailyGain && analysis.daysElapsed && analysis.previousWeight) {
    const weightGain = analysis.average - analysis.previousWeight;
    message += `*GROWTH PERFORMANCE*\n`;
    message += `- Weight Gain: +${weightGain.toFixed(2)} kg (last ${analysis.daysElapsed} days)\n`;
    message += `- Daily Gain: *${analysis.dailyGain.toFixed(0)} g/day*\n`;
    if (analysis.growthRating) {
      message += `- Rating: ${analysis.growthRating}\n`;
    }
    message += `\n`;
  }

  if (analysis.marketStatus) {
    message += `*MARKET READINESS*\n`;
    message += `${analysis.marketStatus}\n\n`;
  }

  if (analysis.recommendation) {
    message += `💡 *Recommendation:* ${analysis.recommendation}\n\n`;
  }

  message += `━━━━━━━━━━━━━━━━━━━━\n`;
  message += `Generated by Ebenezer Farm Manager\n`;
  message += `${new Date().toLocaleString()}`;

  return message;
}

function calculateFlockAge(arrivalDate: string): number {
  const arrival = new Date(arrivalDate);
  const now = new Date();
  const diffDays = Math.floor((now.getTime() - arrival.getTime()) / (1000 * 60 * 60 * 24));
  return Math.floor(diffDays / 7) + 1;
}

function calculatePercentOfTarget(avgWeight: number, weekAge: number, flockType: string): number {
  const targets: Record<string, Record<number, number>> = {
    'Broiler': {
      1: 0.18, 2: 0.42, 3: 0.84, 4: 1.40, 5: 2.05, 6: 2.75, 7: 3.45, 8: 4.10
    },
    'Layer': {
      4: 0.26, 8: 0.67, 12: 1.15, 16: 1.52, 18: 1.68, 20: 1.75
    }
  };

  const target = targets[flockType]?.[weekAge] || avgWeight;
  return (avgWeight / target) * 100;
}

function getUniformityRating(cv: number): string {
  if (cv < 8) return 'Excellent';
  if (cv < 10) return 'Good';
  if (cv < 12) return 'Fair';
  return 'Poor';
}

export function shareViaWhatsApp(message: string, phoneNumber?: string): void {
  const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
  const encodedMessage = encodeURIComponent(message);

  let whatsappURL: string;

  if (phoneNumber) {
    const formattedNumber = phoneNumber.replace(/\s/g, '').replace(/^0/, '+237');
    whatsappURL = `https://wa.me/${formattedNumber}?text=${encodedMessage}`;
  } else if (isMobile) {
    whatsappURL = `whatsapp://send?text=${encodedMessage}`;
  } else {
    whatsappURL = `https://web.whatsapp.com/send?text=${encodedMessage}`;
  }

  window.open(whatsappURL, '_blank');
}

export function shareViaSMS(message: string, phoneNumber?: string): void {
  const encodedMessage = encodeURIComponent(message);
  const smsURL = phoneNumber
    ? `sms:${phoneNumber}?body=${encodedMessage}`
    : `sms:?body=${encodedMessage}`;

  window.location.href = smsURL;
}

export function copyToClipboard(message: string): Promise<void> {
  return navigator.clipboard.writeText(message);
}

interface InsightsMetrics {
  totalExpenses: number;
  totalRevenue: number;
  netProfit: number;
  profitMargin: string;
  costPerBird: number;
  ageWeeks: number;
  ageDays: number;
  birdsAlive: number;
  initialCount: number;
  totalMortality: number;
  mortalityRate: string;
  survivalRate: string;
  totalEggs?: number;
  productionRate?: string;
  dailyAvgCost: number;
  feedConversion: string;
  avgWeight?: number;
  totalWeight?: number;
  dailyWeightGain?: number;
}

interface FlockInfo {
  name: string;
  type: string;
}

export function formatInsightsForWhatsApp(
  metrics: InsightsMetrics,
  flock: FlockInfo,
  farmName: string,
  currencyCode: string,
  eggsPerTray?: number
): string {
  const isLayer = flock.type.toLowerCase() === 'layer';
  const isBroiler = flock.type.toLowerCase() === 'broiler';

  let message = `*📊 FLOCK INSIGHTS REPORT*\n`;
  message += `━━━━━━━━━━━━━━━━━━━━\n\n`;

  message += `*Farm:* ${farmName}\n`;
  message += `*Flock:* ${flock.name} (${flock.type})\n`;
  message += `*Report Date:* ${new Date().toLocaleDateString()}\n\n`;

  message += `*💰 FINANCIAL OVERVIEW*\n`;
  message += `- Total Expenses: *${metrics.totalExpenses.toLocaleString()} ${currencyCode}*\n`;
  message += `- Total Revenue: *${metrics.totalRevenue.toLocaleString()} ${currencyCode}*\n`;
  message += `- Net Profit: *${metrics.netProfit.toLocaleString()} ${currencyCode}*\n`;
  message += `- Profit Margin: ${metrics.profitMargin}%\n`;
  message += `- Cost per Bird: ${metrics.costPerBird.toLocaleString()} ${currencyCode}\n`;
  message += `- Daily Average Cost: ${metrics.dailyAvgCost.toLocaleString()} ${currencyCode}\n\n`;

  message += `*🐔 PRODUCTION METRICS*\n`;
  message += `- Current Age: *Week ${metrics.ageWeeks}* (${metrics.ageDays} days)\n`;
  message += `- Birds Alive: *${metrics.birdsAlive.toLocaleString()}/${metrics.initialCount.toLocaleString()}*\n`;
  message += `- Survival Rate: *${metrics.survivalRate}%*\n`;
  message += `- Mortality: ${metrics.totalMortality} birds (${metrics.mortalityRate}%)\n`;

  if (isLayer && metrics.totalEggs !== undefined) {
    const trays = eggsPerTray ? Math.floor(metrics.totalEggs / eggsPerTray) : 0;
    const loose = eggsPerTray ? metrics.totalEggs % eggsPerTray : metrics.totalEggs;
    message += `- Eggs Collected: *${metrics.totalEggs.toLocaleString()}* (${trays} trays + ${loose} eggs)\n`;
    message += `- Production Rate: *${metrics.productionRate}%*\n`;
  }

  if (isBroiler && metrics.avgWeight !== undefined) {
    message += `- Average Weight: *${metrics.avgWeight.toFixed(2)} kg*\n`;
    message += `- Total Weight: *${metrics.totalWeight?.toFixed(0)} kg*\n`;
    message += `- Daily Gain: ${metrics.dailyWeightGain} g/day\n`;
  }

  message += `\n*📈 EFFICIENCY METRICS*\n`;
  message += `- Feed Conversion: *${metrics.feedConversion}*`;
  if (isBroiler) {
    message += ` kg feed/kg meat\n`;
  } else if (isLayer) {
    message += ` kg feed/kg eggs\n`;
  } else {
    message += `\n`;
  }
  message += `- Cost Efficiency: ${metrics.costPerBird.toLocaleString()} ${currencyCode}/bird\n`;

  message += `\n━━━━━━━━━━━━━━━━━━━━\n`;
  message += `Generated by Ebenezer Farm Manager\n`;
  message += `${new Date().toLocaleString()}`;

  return message;
}
