/*
  Farm Journal — phase 1.

  Two-channel design:

  1. ACTIVITY (auto-logged): every CRUD action across the app fires a
     journal_entries row with author_kind='system' and channel='activity'.
     Body reads like "Three Samples (manager) sold 10 broilers at 5,000
     XAF each — total 50,000 XAF". Owner can soft-delete activity rows
     they don't want to keep but the underlying record (sale, expense,
     etc.) is unaffected.

  2. NOTES (manual): owner / manager / worker / Eden write free-form
     entries. Photos, charts, Eden auto-summaries, milestone callouts
     all live here. Workers can write but the UI nudges this channel
     toward managers and owners — workers' main job is logging real
     actions, which produces Activity entries automatically.

  Mentioning a teammate via @name triggers a push notification when
  that user is on a tier that includes push. Reactions are a cheap way
  for the owner to "👍 acknowledged" a worker's note.

  RLS: anyone on the farm reads; only the author edits/deletes their
  own entry; the farm owner can delete anyone's entry (audit override).
  Private entries are only visible to the author.
*/

-- ── 1. journal_entries ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.journal_entries (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  farm_id      uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  flock_id     uuid NULL REFERENCES public.flocks(id) ON DELETE SET NULL,

  -- Authorship. author_id is NULL when Eden or the system wrote it.
  author_id    uuid NULL REFERENCES public.profiles(id),
  author_role  text NULL,   -- 'owner' | 'manager' | 'worker' — used for the chip
  author_kind  text NOT NULL CHECK (author_kind IN ('user','eden','system')),

  -- Two-channel split. 'activity' rows are auto-generated; 'notes' are
  -- manual or Eden-written. Tabs in the UI filter on this column.
  channel      text NOT NULL CHECK (channel IN ('activity','notes')),

  entry_type   text NOT NULL CHECK (entry_type IN (
    -- notes channel
    'observation','financial','milestone','personal','health','auto_summary',
    -- activity channel (system-generated)
    'sale_logged','expense_logged','feed_logged','mortality_logged',
    'vaccine_logged','flock_created','flock_archived','task_completed',
    'egg_collected','payment_received','team_member_added',
    'inventory_added','withdrawal_cleared','weight_logged','other'
  )),

  -- Display content
  title        text NULL,
  body         text NOT NULL,

  -- Structured payload. For activity rows this carries linked_table and
  -- linked_id so the UI can deep-link back to the underlying record.
  -- e.g. {"linked_table":"sales","linked_id":"<uuid>","amount":50000,"currency":"XAF"}
  metadata     jsonb NOT NULL DEFAULT '{}',
  photo_urls   text[] NOT NULL DEFAULT '{}',

  -- State flags
  is_pinned    boolean NOT NULL DEFAULT false,
  is_private   boolean NOT NULL DEFAULT false,   -- only author + owner see
  is_important boolean NOT NULL DEFAULT false,   -- owner flags for review
  is_deleted   boolean NOT NULL DEFAULT false,   -- soft delete

  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS journal_entries_farm_created_idx
  ON public.journal_entries (farm_id, created_at DESC)
  WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS journal_entries_farm_channel_idx
  ON public.journal_entries (farm_id, channel, created_at DESC)
  WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS journal_entries_flock_idx
  ON public.journal_entries (flock_id, created_at DESC)
  WHERE flock_id IS NOT NULL AND is_deleted = false;

COMMENT ON TABLE  public.journal_entries IS 'Per-farm timeline of actions (auto) and notes (manual). Two-channel: activity, notes.';
COMMENT ON COLUMN public.journal_entries.channel IS 'activity = auto-generated by app actions; notes = manual or Eden-written';
COMMENT ON COLUMN public.journal_entries.metadata IS 'For activity rows: linked_table + linked_id for deep-linking. For Eden rows: model + tokens used.';

-- updated_at auto-refresh trigger
CREATE OR REPLACE FUNCTION public.journal_entries_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_journal_entries_touch ON public.journal_entries;
CREATE TRIGGER trg_journal_entries_touch
  BEFORE UPDATE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.journal_entries_touch_updated_at();

-- ── 2. journal_reactions ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.journal_reactions (
  entry_id   uuid NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  emoji      text NOT NULL,    -- single emoji ✓ 👍 ❤️ 🚨 🎉 etc.
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (entry_id, user_id, emoji)
);

CREATE INDEX IF NOT EXISTS journal_reactions_entry_idx
  ON public.journal_reactions (entry_id);

-- ── 3. journal_mentions ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.journal_mentions (
  entry_id          uuid NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  mentioned_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  notified_at       timestamptz NULL,   -- NULL = push hasn't fired yet
  PRIMARY KEY (entry_id, mentioned_user_id)
);

CREATE INDEX IF NOT EXISTS journal_mentions_user_pending_idx
  ON public.journal_mentions (mentioned_user_id)
  WHERE notified_at IS NULL;

-- ── 4. RLS ──────────────────────────────────────────────────────────────

ALTER TABLE public.journal_entries   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_mentions  ENABLE ROW LEVEL SECURITY;

-- Helper: is the current user on the farm (owner or member)?
-- Reuses the membership pattern from existing RLS.
DROP POLICY IF EXISTS journal_entries_select ON public.journal_entries;
CREATE POLICY journal_entries_select ON public.journal_entries
  FOR SELECT
  USING (
    is_deleted = false
    AND (
      -- Public to the farm UNLESS the entry is private
      (is_private = false AND EXISTS (
        SELECT 1 FROM public.farm_members fm
        WHERE fm.farm_id = journal_entries.farm_id
          AND fm.user_id = auth.uid()
      ))
      OR
      -- Private entries: only the author + the farm owner see
      (is_private = true AND (
        author_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM public.farms f
          WHERE f.id = journal_entries.farm_id
            AND f.owner_id = auth.uid()
        )
      ))
    )
  );

DROP POLICY IF EXISTS journal_entries_insert ON public.journal_entries;
CREATE POLICY journal_entries_insert ON public.journal_entries
  FOR INSERT
  WITH CHECK (
    -- Author must be the current user (or NULL for system/eden inserts
    -- which only happen via service_role bypassing RLS)
    author_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.farm_members fm
      WHERE fm.farm_id = journal_entries.farm_id
        AND fm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS journal_entries_update ON public.journal_entries;
CREATE POLICY journal_entries_update ON public.journal_entries
  FOR UPDATE
  USING (
    author_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.farms f
      WHERE f.id = journal_entries.farm_id
        AND f.owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS journal_entries_delete ON public.journal_entries;
CREATE POLICY journal_entries_delete ON public.journal_entries
  FOR DELETE
  USING (
    -- Soft delete via UPDATE is the preferred path; hard delete only
    -- for the farm owner (audit cleanup, GDPR requests).
    EXISTS (
      SELECT 1 FROM public.farms f
      WHERE f.id = journal_entries.farm_id
        AND f.owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS journal_reactions_select ON public.journal_reactions;
CREATE POLICY journal_reactions_select ON public.journal_reactions
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.journal_entries je
      JOIN public.farm_members fm ON fm.farm_id = je.farm_id
      WHERE je.id = journal_reactions.entry_id
        AND fm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS journal_reactions_insert ON public.journal_reactions;
CREATE POLICY journal_reactions_insert ON public.journal_reactions
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.journal_entries je
      JOIN public.farm_members fm ON fm.farm_id = je.farm_id
      WHERE je.id = journal_reactions.entry_id
        AND fm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS journal_reactions_delete ON public.journal_reactions;
CREATE POLICY journal_reactions_delete ON public.journal_reactions
  FOR DELETE
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS journal_mentions_select ON public.journal_mentions;
CREATE POLICY journal_mentions_select ON public.journal_mentions
  FOR SELECT
  USING (mentioned_user_id = auth.uid());

DROP POLICY IF EXISTS journal_mentions_insert ON public.journal_mentions;
CREATE POLICY journal_mentions_insert ON public.journal_mentions
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.journal_entries je
      WHERE je.id = journal_mentions.entry_id
        AND je.author_id = auth.uid()
    )
  );

-- ── 5. Storage bucket for journal photos ────────────────────────────────
--
-- We reuse the existing 'eden-photos' bucket pattern. The bucket itself
-- is created by an earlier migration; this just ensures journal entries
-- inherit the same RLS path. Photos are uploaded to
-- eden-photos/journal/{farm_id}/{entry_id}/{filename}
--
-- No bucket DDL needed here.
